version: "3.9"

services:
  node:
    build: .
    command: sh -c "yarn start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/myapp
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  yarn-cache:
